<a href="https://colab.research.google.com/github/PhanDangSiNguyen/ThucHanhToanCaoCap/blob/main/BaiTapChuong5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1

In [1]:
x = 3 
print (x)

3


In [5]:
import math
x = math.sqrt(1+x) 
print (x) 

2.0


In [6]:
x = math.sqrt(1+x)
print (x) 

1.7320508075688772


In [7]:
x = math.sqrt(1+x)
print (x) 

1.6528916502810695


Bài 2

In [11]:
import math 
x = 3
lap = 1
while (x != math.sqrt(x+1)): 
  x = math.sqrt(x+1) 
  lap = lap  +1   
x

1.618033988749895

In [12]:
lap

32

Bài 3

In [13]:
import sympy as sp
from sympy import Symbol
x = Symbol('x')
sp.solve(x-sp.sqrt(1+x),x) 

[1/2 + sqrt(5)/2]

Bài 4

In [14]:
import numpy as np
v1 = np.array([1., 2., 3.])
v2 = np.array([2., 1., 0.]) 
v3 = v1 + v2 
v3

array([3., 3., 3.])

In [15]:
3*v1  + 2*v2 

array([7., 8., 9.])

In [16]:
[1, 2, 3] + [2, 1, 0] 

[1, 2, 3, 2, 1, 0]

In [17]:
3*[1, 2, 3] + 2*[2, 1, 0] 

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

Ghép nối

In [20]:
v4 = np.hstack([v1, v2]) 
v4

array([1., 2., 3., 2., 1., 0.])

Phép nhân vô hướng

In [21]:
np.dot(v1, v2) 

4.0

In [ ]:
Tính toán giá trị sin của vector

In [22]:
angles = np.linspace(0, np.pi/2, 5)
angles 

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [23]:
np.sin(angles)

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

In [24]:
import sympy as sy
sy.sin(angles

SyntaxError: ignored

In [25]:
from sympy import sin as sysin
angles = np.linspace(0, np.pi/2, 5) 
sinangle = np.zeros(5)
len(angles)
for i in range(len(angles)): 
  sinangle[i] = sysin(angles[i]) 
sinangle     

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

Bài 5

In [30]:
import numpy as np
goc = np.pi/3
A = np.array([ [np.cos(goc), -np.sin(goc)],                      
              [np.sin(goc),  np.cos(goc)] ])
V = np.array([1. , 0. ])
Y = np.dot(A, V)
Y 

array([0.5      , 0.8660254])

Bài 10